name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: $(System.DefaultWorkingDirectory)/TestResults/

      - name: Format Code
        run: dotnet format --check

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: |
          cd src/OldPhonePadApp
          doxygen Doxyfile

      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: src/OldPhonePadApp/docs/html

  create-release:
    if: github.event_name == 'push'
    needs: [build-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build the project
        run: |
          dotnet publish -c Release -o ./publish

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Release for ${{ github.ref_name }}"
          artifacts: ./publish/**
          token: ${{ secrets.GITHUB_TOKEN }}

